<?php

/**
 * @file
 * Contains ethereum_user_connector.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function ethereum_user_connector_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ethereum_user_connector module.
    case 'help.page.ethereum_user_connector':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal Drupal user connector enables Drupal Users to verify an Ethereum account address.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Provide default value callback.
 */
function ethereum_user_connector_default_status () {
  return 0;
}

/**
 * Pre save handler.
 *
 * If a user has submitted an address generate a hash and set the validation status.
 */
function ethereum_user_connector_user_presave(EntityInterface $entity) {

  $last_address =    $entity->original->field_ethereum_address->getValue()[0]['value'];
  $curr_address = $entity->field_ethereum_address->getValue()[0]['value'];

  if ($last_address !== $curr_address) {
    $hash = md5($GLOBALS['base_url'] . $curr_address);
    $entity->field_ethereum_drupal_hash->set(0, $hash);
    $entity->field_ethereum_address_status->set(0, 1);
  }
}
