<?php

/**
 * @file
 * Contains ethereum.module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\ethereum\Entity\EthereumServer;
use League\CommonMark\CommonMarkConverter;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ethereum_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ethereum_user_connector module.
    case 'help.page.ethereum':
      return ethereum_get_readme_html('ethereum');
    default:
  }
}

/**
 * Implements hook_help().
 */
function ethereum_get_readme_html($module) {
  $path = drupal_get_path('module', $module) . '/Readme.md';
  $readme = @file_get_contents(DRUPAL_ROOT . '/'. $path);
  if($readme === FALSE) {
    return "<div class='messages messages--warning'>Missing Readme.md for $path.</div>";
  }
  else {
    $converter = new CommonMarkConverter();
    return $converter->convertToHtml($readme);
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function ethereum_field_formatter_info_alter(array &$info) {
  // Allow the 'Ethereum address' field type to use the existing 'Basic string'
  // formatter.
  $info['basic_string']['field_types'][] = 'ethereum_address';
}

/**
 * Implements hook_js_settings_alter().
 */
function ethereum_js_settings_alter(&$settings, AttachedAssetsInterface $assets) {
  // Provide the URL of the current server in drupalSettings to allow JavaScript
  // code to rely on an instantiated Web3 object.
  $current_server = \Drupal::config('ethereum.settings')->get('current_server');
  $settings['ethereum']['currentServerHost'] = EthereumServer::load($current_server)->getUrl();
}
