ethereum_smartcontract.contract.*:
  type: config_entity
  label: 'Smart Contract config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    contract_src:
      type: string
      label: 'Contract Source file (relative path to ethereum_smartcontract directory).'
    abi:
      type: string
      label: 'Smart contract ABI'
    networks:
      type: sequence
      label: 'Contract addresses by network id.'
      sequence:
        -  type: string
           label: '<network_id> => <contract address>'
    is_imported:
      type: bool
      label: 'Contract was imported from Truffle'
    imported_file:
      type: string
      label: 'Full path to the imported JSON file if applicable.'
